### ISSUE TITLE
v0.5.0

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#114]
I'd say we're a little overdue our next release. It would be good to close the following issues first:

- [x] https://github.com/PlasmaFAIR/fortitude/issues/95
- [x] https://github.com/PlasmaFAIR/fortitude/issues/29

Another minor problem: A fix diff is displayed for `superfluous-implicit-none`, and the output claims that running `--fix` will correct it, but this isn't yet implemented. There are a few possible solutions:
  - Implement fixes before the next release, possibly hidden behind the `--preview` setting
  - Edit the message to say fixes are coming soon
  - Hide the message for now

**Comment by ZedThree** [comment]
On the last point, maybe just remove the diff but keep the `= help` for now?

**Comment by LiamPattinson** [comment]
One more thing I think we should get in before 0.5:

- [ ] https://github.com/PlasmaFAIR/fortitude/issues/118 revealed a bug in the config file reader, and though I attempted to fix it in https://github.com/PlasmaFAIR/fortitude/pull/119, this just seemed to add more bugs than it fixed. We should probably write a more robust config file reader and handle the merge with CLI args manually.

---

> On the last point, maybe just remove the diff but keep the `= help` for now?

Perhaps, but I would like there to be a displayed diff at some point. I know ruff doesn't print diffs by default, but clippy does, and I find those more helpful than the sometimes-vague suggestions that ruff provides.

**Comment by ZedThree** [comment]
Sorry, yes I meant just hide it for now, but still display the `= help`
