### ISSUE TITLE
format is confusing when output to the CLI is redirected / piped

### ISSUE THREAD

**Issue by nbehrnd** [PlasmaFAIR/fortitude#122]
When redirecting the output from the CLI to `less`, the report includes control characters -- is there a working mode which does not not display them?

Fortitude indicates each spot which should be improved further, including a reference to the corresponding rule.  Compared to the report straight to the CLI, If I pipe this output to `less` by 

```shell
fortitude check minimal.f90 | less
```

(because the then available vim navigation by `j`, `k`, `gg`, `G` potentially in parallel to a second pane), additional characters show up.  This is more difficult to read, than the original version:

![2024-11-18_fortitude_piped](https://github.com/user-attachments/assets/45ed3325-1788-4c5a-9657-cc4b6729d5a5)

This observation appears to be consistent with a redirect into a record e.g. by `fortitude check minimal.f90 > out.txt`, though I do not intend to use the checker _this way_.

Setup: Linux Debian 13/trixie with less (643), GNU bash (5.2.32), xfce4-terminal 1.1.3 (Xfce 4.18); and  fortitude (0.4.0, fetched from PyPI).

[minimal.f90.txt](https://github.com/user-attachments/files/17802455/minimal.f90.txt)

**Comment by ZedThree** [comment]
Thanks for the bug report @nbehrnd! This is fixed in #117, which will be in the next release.

**Comment by nbehrnd** [comment]
@ZedThree Thank you for the hint.  With a bookmark for the entry on [PyPI](https://pypi.org/project/fortitude-lint/) added; if the update is added there .and. I can observe locally the issue were gone, I'll close this this thread.
