### ISSUE TITLE
Recommend `implicit none (type, external)`

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#140]
This is a Fortran 2018 feature for preventing implicit procedures. The big compilers all support it: https://godbolt.org/z/hn36GjEqh
Notably `nvfortran` doesn't, so this would be an issue for CUDA projects.

Use case is something like

```f90
program foo
  implicit none

  call unknown_func() ! This compiles! (but may not link)
end program foo
```

```f90
program foo
  implicit none (external)

  call unknown_func() ! This won't compile
end program foo
```

This probably wants to be a separate rule to `implicit-typing` because not all compilers support it

**Comment by LiamPattinson** [comment]
That's a cool feature, would have saved me a few headaches when encountering some baffling linker errors. Would probably be an easy (unsafe) fix too.
