### ISSUE TITLE
Warn about modules without `private` statements

### ISSUE THREAD

**Issue by Beliavsky** [PlasmaFAIR/fortitude#147]
I think it's a good idea to have a private statement in a module, requiring the programmer to explicitly list the public entities, so I request that fortitude have an option to warn about a module such as the one below.

```
module m
implicit none
integer :: i
end module m
```

If such a warning is added, whether it should be turned on by default is a matter of taste.

**Comment by LiamPattinson** [comment]
I fully agree with this! It's something I aim for in my own code, but I'm unsure if it should be part of the default rule set.

Following this, we could implement another rule to check for 'dead code' (types/procedures that aren't used anywhere), as it's likely a bug if something isn't used within a module and isn't exported. If everything in a module is public by default, it becomes much harder to catch that sort of error.
