### ISSUE TITLE
Suggest that statement functions be made into internal functions

### ISSUE THREAD

**Issue by Beliavsky** [PlasmaFAIR/fortitude#157]
Periodically on Fortran Discourse, most recently at https://fortran-lang.discourse.group/t/anonymous-functions/8903, someone new to Fortran asks what some code with statement functions is doing. They are now obsolescent and should be warned about, as in the code

```Fortran
program mwe1
    implicit none
    double precision :: f,x
    f(x)= x**2 + 1.0d0
    print *, f(2.0d0)
end program mwe1
```

for which fortitude says only

```
xstatement_func.f90:3:5: P011 prefer 'real(real64)' to 'double precision' (see 'iso_fortran_env')
  |
1 | program mwe1
2 |     implicit none
3 |     double precision :: f,x
  |     ^^^^^^^^^^^^^^^^ P011
4 |     f(x)= x**2 + 1.0d0
5 |     print *, f(2.0d0)
  |


fortitude: 1 files scanned.
Number of errors: 1
```

**Comment by ZedThree** [comment]
Definitely! I think we'll likely add a whole category for obsolescent features, including label `do` loops and computed go-tos
