### ISSUE TITLE
Move `double-precision` rule to `Obsolesent` category

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#166]
The 'explain' text for the rule `double-precision` states:

```rust
/// The `double precision` type does not guarantee a 64-bit floating point number
/// as one might expect, and instead is only required to have a higher decimal
/// precision than the default `real`, which may vary depending on your system
/// and can be modified by compiler arguments.
```

This justifies its inclusion in the `Precision` rule category, but in practice a `double precision` will be a 64-bit floating point 99.99...% of the time. A better justification for its removal from modern code is that the `real(kind)` system is more flexible and consistent with the way other types are handled. Perhaps the new `Obsolescent` category would be more appropriate?

**Comment by ZedThree** [comment]
The standard has formally obsolescent and deleted features, so I think we should reserve this category for those. Here's the full list from the 2023 standard:

1) Alternate return — see B.3.2.
2) Computed GO TO — see B.3.3.
3) Statement functions — see B.3.4.
4) DATA statements amongst executable statements — see B.3.5.
5) Assumed length character functions — see B.3.6.
6) Fixed form source — see B.3.7.
7) CHARACTER* form of CHARACTER declaration — see B.3.8.
8) ENTRY statements — see B.3.9.
9) Label form of DO statement – see B.3.10.
10) COMMON and EQUIVALENCE statements, and the block data program unit – see B.3.11.
11) Specific names for intrinsic functions – see B.3.12.
12) FORALL construct and statement – see B.3.13

**Comment by LiamPattinson** [comment]
That's a fair point, Modern Fortran (2018) lists `double precision` as 'deprecated' but not obsolescent. I'll leave it where it is for now.

**Comment by ZedThree** [comment]
Might make sense to have a `Deprecated` category as well? Not formally declared obsolete but still discouraged? Although, that's possibly quite broad and might apply to everything!

**Comment by LiamPattinson** [comment]
```rust
/// ## What it does
/// Checks for Fortran.
///
/// ## Why is this bad?
/// Because it's <insert_year>.
///
/// ## References
/// - Half the people I talk to at conferences
#[violation]
pub struct Everything {}

impl Violation for Everything {
    #[derive_message_formats]
    fn message(&self) -> String {
        format!("Have you considered rewriting this in C++?")
    }
}

impl AstRule for Everything {
    fn check(_settings: &Settings, node: &Node, _src: &SourceFile) -> Option<Vec<Diagnostic>> {
        some_vec![Diagnostic::from_node(Everything {}, node)]
    }

    fn entrypoints() -> Vec<&'static str> {
        vec!["translation_unit"]
    }
}
```

**Comment by ZedThree** [comment]
Liam, come on! `s/C++/Rust/`, please!
