### ISSUE TITLE
Warn about missing space in `doubleprecision`, `enddo`, `endif` etc.

### ISSUE THREAD

**Issue by Beliavsky** [PlasmaFAIR/fortitude#178]
I don't know what the precise terminology is, but Fortran allows some two-word keywords such as `double precision`, `end do`, `end if` to be written without the space as `doubleprecision`, `enddo`, `endif`. I think omitting the space makes the code less readable and that should be an option to warn about (and ideally fix) such usage.

**Comment by ZedThree** [comment]
We agree! This is a duplicate of #66
