### ISSUE TITLE
Warn about repeated literals, especially integers used to declare arrays

### ISSUE THREAD

**Issue by Beliavsky** [PlasmaFAIR/fortitude#180]
For the code
```fortran
implicit none
real(8) :: probs(221), cnorm(221), beta(4,221), crits(221), wght(221)
end
```
fortitude does not complain about the repeated `221`, which should be a named constant. The code was taken from

https://github.com/cran/urca/blob/master/src/UnitRootMacKinnon.f

**Comment by ZedThree** [comment]
A stricter version just warning about magic numbers as array sizes would be simpler to implement and still worthwhile I think. 

`ruff` has [`magic-value-comparison`](https://docs.astral.sh/ruff/rules/magic-value-comparison/) which checks for literals in comparisons, while `clang-tidy` has [`readability-magic-numbers`](https://clang.llvm.org/extra/clang-tidy/checks/readability/magic-numbers.html) which is even wider, pretty much just checking for number literals outside of assignments (although with options to ignore certain values).

Probably more nuance than `clang-tidy` would be nicer, but this could be through multiple rules: `magic-array-size`, `magic-value-comparison`, etc.
