### ISSUE TITLE
Whitespace before inline comments

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#189]
Other language style guides recommend two spaces before inline comments:

```f90
x = x + 1! bad
x = x + 1 ! better
x = x + 1  ! good
```

This more clearly distinguishes code from comments, improving readability.

This would also address an issue introduced by PR https://github.com/PlasmaFAIR/fortitude/pull/185, which introduced automatic fixes for unnamed end statements. It was found that if they're followed by an inline comment these fixes also remove any whitespace between the end statement and the comment, significantly hurting readability (ultimately I think this is a tree-sitter problem).

**Comment by LiamPattinson** [comment]
Ideally this sort of thing should be fixed by a `fortitude format` call, but as it's possible for rule fixes to introduce errors like this, I think it would be best to duplicate the functionality into the linter too.

**Comment by ZedThree** [comment]
Ah, the tree-sitter node is up to the start of the comment because most statements include a grammar rule `_end_of_statement`. This is either:

- semicolon
- end of line
- start of comment

This is a bit of a fiddly thing, unfortunately.
