### ISSUE TITLE
v0.6.0

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#202]
Some pretty big changes in this one!

- Auto-fixes (!!!)
- Preview mode
- Many more output formats
- A bunch of new rules
- ~~A super-cool and not at all superfluous progress bar~~

That seems like a good amount for a new release. @ZedThree Is there anything else you think we need?

I'd also like to decide which features should come out of preview mode, if any. I was thinking:

- `missing-double-colon`
- `incorrect-space-before-comment`
- `statement-function`
- `common-block`
- `entry-statement`
- `external-procedure` (though this might be the most controversial of the lot)

I think it would be best to leave the accessibility statement rules under preview mode until we implement a nice way to keep very opinionated rules out of default rule set. Similarly for `implicit-external-procedures`.

Alternatively, as `--preview` is itself a new feature, we could leave everything hidden behind preview mode until v0.7.0. Thoughts?

**Comment by ZedThree** [comment]
Yep, I think we're in a good place to make a new release. There's always new rules to add, but they can wait.

I think all the `OB` ones can definitely come out of preview. The others on your list should also be fine I think.

Maybe we should list the rules in the README (till we make proper docs) -- could just do the table like here: https://docs.astral.sh/ruff/rules/
