### ISSUE TITLE
readme's version 0.6.0 isn't tagged / documention fell out of sync

### ISSUE THREAD

**Issue by nbehrnd** [PlasmaFAIR/fortitude#211]
Perhaps this is due to an omitted `--follow-tags` during a push to the repository, or for an early preview.  However `README.md` in branch `main` (at commit [cd32010](https://github.com/PlasmaFAIR/fortitude/commit/cd3201039848d775fdd9448eafe3402924b77e34) by December 6th) states more than once `Added in v0.6.0` while there isn't yet a corresponding tag in the public commit history, and in consequence no new (past November 22nd) release here, nor on PyPI.  Please keep them in sync.

**Comment by ZedThree** [comment]
0.6.0 is the upcoming release, will be out this week!
