### ISSUE TITLE
Warn if there is no default case in a select statement

### ISSUE THREAD

**Issue by imciner2** [PlasmaFAIR/fortitude#213]
It is good practice to include a default case in a select statement to catch unknown values and either handle them appropriately or flag an error.

**Comment by ZedThree** [comment]
Yes, great idea, thanks @imciner2!

I was thinking the best version of this rule would actually be like rust's, which is a compile error if `match` expressions don't cover all possible values, however I suspect this is a) difficult in general with Fortran, and b) even harder currently in fortitude without more semantic information.

Looking at `clang-tidy`, they have [`bugprone-switch-missing-default-case`](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/switch-missing-default-case.html) which is basically exactly as you propose, except for `enum`s where they can actually check all possible values. Fortran 2023 introduced `enumeration type` and named `enum`s, both of which it _should_ be possible to check that `select case` is exhaustive for, but it looks like no compilers have actually implemented either of them yet -- the tree-sitter grammar doesn't yet for that matter.

We should have three variations on this, for `select case`, `select type` and `select rank`
