### ISSUE TITLE
Proper integrated tests needed

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#29]
Currently using the file `test.f90` to manually check everything works on a real Fortran file. Some real tests would be preferable.

**Comment by ZedThree** [comment]
Also need this for proper testing of the interaction between the configuration file and CLI args

**Comment by ZedThree** [comment]
https://rust-cli.github.io/book/tutorial/testing.html#testing-cli-applications-by-running-them
