### ISSUE TITLE
Catch missing `intent` attribute

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#40]
Procedure arguments should have `intent` attributes. Default is `intent(inout)`, this could be an auto-fix. In principle it should also be possible to work out if this could be more specifically `intent(in)` or `intent(out)`, based on whether the arguments are only ever read from/written to

**Comment by LiamPattinson** [comment]
Good idea, but I'd be wary of auto-fixing it to `intent(inout)` unless we can guarantee that that was actually the intent. I've seen code where `intent(in)` should have been obvious but the author either forgot to add intent, didn't know about intent, or was too lazy to add it.
