### ISSUE TITLE
Project-wide settings

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#5]
It should be possible to choose settings for a whole Git project via a top-level settings file -- perhaps `.fortitude.toml`? This should include the same fields as the optional CLI arguments. The following features will be required:

- [ ] Toml reader, or some other choice of settings file format.
- [ ] Function to merge command line settings with those from the settings file.
  - Command line arguments should always take precedence, but in some cases should be additive, such as when including rules.
- [ ] A function to find a `.fortitude.toml` file for a project.
  - Search up directories until finding one that contains `.fortitude.toml` or the `.git` directory.

(edit: 2024-09-19, updated bullet points that no longer make sense)

**Comment by ZedThree** [comment]
And/or use `extra.fortitude` in `fpm.toml`? See https://fpm.fortran-lang.org/spec/manifest.html#additional-free-data-field

This is an option in Ford: https://forddocs.readthedocs.io/en/stable/user_guide/project_file_options.html#fpm-toml-file

**Comment by LiamPattinson** [comment]
Good shout! Since there are a lot of Fortran/Python projects around nowadays, and this is installable via `pip`, I was thinking about also allowing `[tool.fortitude]` in `pyproject.toml`.

**Comment by ZedThree** [comment]
Spent some time today looking into this, how ruff does it, are there any libraries that automate this.

Ruff is ridiculously complex here. They support a complicated hierarchy of config files, they have lots of commands with lots of arguments, global options, etc etc, which all makes it really difficult to work out what's going on.

There are lots of half-finished or abandoned libraries out there that aim/claim to combine clap and toml. Not really sure how any of them combine with subcommands.

The most straightforward approach is probably to use clap's builder approach and set the default for the command line from the toml file.

**Comment by LiamPattinson** [comment]
That sounds like a good way to handle it, as the command line should always take precedence. I think the final rule set should be built up as follows:

- Start with the default rule set
- Modify this rule set using config file rule choices, if present:
  - `include` should add rules to the default rule set
  - `ignore` should remove rules from the default rule set
  - `select` should overwrite the default rule set, and cannot be combined with `include`/`ignore`.
- Take the rule set from the config file (or the default rule set if no config file was found), modify it from the command line:
  - `--include` should add rules
  - `--ignore` should remove them
  - `--select` should overwrite the config file rule set, and can't be combined with `--include`/`--ignore`. However, it should still be compatible with `include`/`ignore` in the config file, as its usage on the command line will just ignore whatever is in those lists.

There are other layers of complexity that we probably don't have to worry about in the first instance:

- Handle users specifying things like `--ignore=T` to ignore all typing rules
- How do we handle conflicts, like `--include=T001 --ignore=T`? Or even just `--include=S001 --ignore=S001`?
- At some point we should introduce rule tiers, like how Ruff has default, preview, deprecated, etc. We could begin with a very simple hierarchy:

  - Default (uncontroversial rules)
  - Pedantic (more opinionated rules that you could take or leave)

  The question then becomes, if the user chooses `--include=T`, but hasn't switched on pedantic mode, should they still get pedantic typing rules? Ruff won't switch on 'preview' rules unless you explicitly switch on preview mode, and I think deprecated rules have to be switched on individually.
- I'm not sure how to accommodate per-file rule sets in the current design of the code.
