### ISSUE TITLE
Per-file ignores

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#6]
It should be possible to ignore rules on a per-file and per-line basis.

- To ignore rules per file, will need to add project-wide settings file first (https://github.com/PlasmaFAIR/fortitude/issues/5). It will be easier to handle this via a settings file or the command line than to parse comments in the files themselves.
- ~~Per-line ignores could be done the same way as flake8/ruff: search for a comment `! noqa` at the end of a line. The regex `!\w*noqa\w*$` should do it.~~
  - ~~After gathering rule violations for a file, check the returned line numbers, and search for `! noqa` on those lines. Discard violations wherever it's found.~~
  - ~~Could also have fine-grained ignores, such as `! ignore: E123`.~~
  - ~~Things will get trickier if we also aim to account for line continuations with `&`.~~

Edit: To aid project management, this Issue should just be for the per-file ignores, as these features can be tackled independently

**Comment by jatkinson1000** [comment]
Adding a +1 for the option to ignore rules on a file-by-file basis.

**Comment by LiamPattinson** [comment]
This is next up on our priorities list, and we've been giving the per-line ignores some more thought.

- We're thinking about going for something like `! allow(all)` as a general 'nolint' statement, and e.g. `! allow(line-too-long)` for specific allowances.
- This should go on the line _before_ the offending line(s). We probably won't have an inline equivalent in the first instance.
- To implement this, we should find all comments that match the required format, and if a violation is raised within the range of the next AST sibling, it should be discarded.
  - This will allow you to put the comment at the top of a function/module to ignore all issues within it!
