### ISSUE TITLE
Initialisation in declaration should require explicit `save`

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/fortitude#60]
Initialisation in declarations gets an implicit `save`, meaning the initialisation is not done on subsequent entry into the routine.

Bad:

```fortran
subroutine foo()
  integer :: bar = 1
end subroutine
```

Good:

```fortran
subroutine foo()
  integer, save :: bar = 1
end subroutine
```

Also good:

```fortran
subroutine foo()
  integer :: bar
  bar = 1
end subroutine
```

**Comment by LiamPattinson** [comment]
Glad you've raised this, because I wasn't aware of this behaviour. Might have to go back to edit some old code I wrote...
